COMMAND_META: dict[str, tuple[str, str]] = {
    #  command           args hint              description
    "hello":          ("",                    "Greet the bot"),
    "help":           ("",                    "Show all available commands"),
    "add":            ("[name] [phone]",       "Add by name (+optional phone), or 'add' alone for full interactive entry"),
    "change":         ("[name] [old] [new]",   "Change phone number"),
    "phone":          ("[name]",               "Show phone number(s)"),
    "all":            ("",                    "Show all contacts"),
    "delete-contact": ("[name]",               "Delete a contact"),
    "delete-phone":   ("[name] [phone]",       "Remove a specific phone"),
    "add-email":      ("[name] [email]",       "Add email to a contact"),
    "add-birthday":   ("[name] [DD.MM.YYYY]",  "Add birthday"),
    "show-birthday":  ("[name]",               "Show birthday"),
    "birthdays":      ("[days]",               "Upcoming birthdays (default: 7 days)"),
    "find":           ("[query]",              "Search contacts by name or phone"),
    "add-note":       ("[name] [text]",        "Add a note to a contact"),
    "edit-note":      ("[name]",               "Edit a note by ID"),
    "delete-note":    ("[name]",               "Delete a note by ID"),
    "show-notes":     ("[name]",               "Show all notes for a contact"),
    "show-all-notes": ("",                    "Show all notes across all contacts"),
    "all-with-notes": ("",                    "Show all contacts with all fields including notes"),
    "find-notes":     ("[query]",              "Search notes across all contacts"),
    "add-tag":        ("[name]",               "Add a tag to a contact's note"),
    "find-by-tag":    ("[tag]",                "Search notes by a specific tag"),
    "sort-by-tags":   ("",                    "Show all notes sorted by tags"),
    "export-book":    ("[csv|json] [path]",   "Export address book to CSV or JSON file"),
    "close":          ("",                    "Quit the bot"),
    "exit":           ("",                    "Quit the bot"),
}
